

SELECT c.AUTHOR_ID, a.AUTHOR_NAME, c.CATEGORY, SUM(c.TOTAL_PRICE) AS TOTAL_SALES
FROM AUTHOR a, (SELECT b.CATEGORY AS CATEGORY, b.AUTHOR_ID AS AUTHOR_ID, b.BOOK_ID AS BOOK_ID, SUM(bs.SALES) * b.PRICE AS TOTAL_PRICE
FROM BOOK b, BOOK_SALES bs
WHERE b.BOOK_ID = bs.BOOK_ID AND bs.SALES_DATE BETWEEN '2022-01-01' AND '2022-01-31'
GROUP BY b.CATEGORY, b.AUTHOR_ID, b.BOOK_ID) c
WHERE a.AUTHOR_ID = c.AUTHOR_ID
GROUP BY c.CATEGORY, a.AUTHOR_NAME, c.AUTHOR_ID
ORDER BY c.AUTHOR_ID, c.CATEGORY DESC