
SELECT i.ITEM_ID, i.ITEM_NAME, i.RARITY
FROM ITEM_INFO i
WHERE i.ITEM_ID NOT IN
(SELECT PARENT_ITEM_ID as ITEM_ID
FROM ITEM_TREE
WHERE PARENT_ITEM_ID IS NOT NULL
GROUP BY PARENT_ITEM_ID)
ORDER BY i.ITEM_ID DESC