
SELECT ID,
(CASE b
    WHEN 1 THEN 'CRITICAL'
    WHEN 2 THEN 'HIGH'
    WHEN 3 THEN 'MEDIUM'
    WHEN 4 THEN 'LOW'
END) AS COLONY_NAME
FROM (SELECT ID, NTILE(4) OVER(ORDER BY SIZE_OF_COLONY DESC) AS b FROM ECOLI_DATA) a
ORDER BY ID;