-- 코드를 입력하세요



SELECT a.CAR_ID,
(CASE COUNT(b.COUNT)
    WHEN 0 THEN '대여 가능'
    ELSE '대여중'
END)
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY a LEFT OUTER JOIN (SELECT CAR_ID, COUNT(CAR_ID) AS COUNT
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE START_DATE <= '2022-10-16' AND END_DATE >= '2022-10-16'
GROUP BY CAR_ID) b
ON a.CAR_ID = b.CAR_ID
GROUP BY a.CAR_ID
ORDER BY a.CAR_ID DESC