-- 코드를 입력하세요

SELECT MONTH(a.START_DATE) AS MONTH, a.CAR_ID AS CAR_ID, COUNT(a.CAR_ID) AS RECORDS

FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY a, 
(SELECT CAR_ID, COUNT(CAR_ID) AS COUNT
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE START_DATE BETWEEN '2022-08-01' AND '2022-10-31'
GROUP BY CAR_ID) b

WHERE a.CAR_ID = b.CAR_ID AND b.COUNT >= 5 AND a.START_DATE BETWEEN '2022-08-01' AND '2022-10-31'
GROUP BY MONTH(a.START_DATE), a.CAR_ID
HAVING COUNT(a.CAR_ID) > 0
ORDER BY MONTH(a.START_DATE) ASC, a.CAR_ID DESC