

SELECT YEAR(DIFFERENTIATION_DATE) AS YEAR, (b.MAX - a.SIZE_OF_COLONY) AS YEAR_DEV, a.ID
FROM ECOLI_DATA a, (SELECT YEAR(DIFFERENTIATION_DATE) AS YEAR, MAX(SIZE_OF_COLONY) AS MAX 
FROM ECOLI_DATA
GROUP BY YEAR(DIFFERENTIATION_DATE)) b
WHERE YEAR(a.DIFFERENTIATION_DATE) = b.YEAR
ORDER BY YEAR(a.DIFFERENTIATION_DATE), (b.MAX - a.SIZE_OF_COLONY)