

SELECT i.ID, t.FISH_NAME, i.LENGTH
FROM FISH_INFO i, FISH_NAME_INFO t,
( SELECT n.FISH_NAME as FISH_NAME, MAX(i.LENGTH) as MAX
FROM FISH_INFO i, FISH_NAME_INFO n
WHERE i.FISH_TYPE = n.FISH_TYPE
GROUP BY n.FISH_NAME) m
WHERE i.FISH_TYPE = t.FISH_TYPE AND t.FISH_NAME = m.FISH_NAME
AND i.LENGTH = m.max
ORDER BY i.ID