-- 코드를 입력하세요

SELECT a.CATEGORY AS CATEGORY, a.PRICE AS MAX_PRICE, a.PRODUCT_NAME AS PRODUCT_NAME
FROM FOOD_PRODUCT a, (SELECT CATEGORY, MAX(PRICE) AS MAX
FROM FOOD_PRODUCT
WHERE CATEGORY IN ('과자', '국', '김치', '식용유')
GROUP BY CATEGORY) b
WHERE a.CATEGORY = b.CATEGORY AND a.PRICE = b.MAX
ORDER BY a.PRICE DESC